<?php
$finwertServices = [
    'startup-solutions' => [
        'title' => 'Startup Solutions',
        'short' => 'Finance, compliance, and setup support for early-stage companies.',
        'overview' => 'Finwert offers start-up consulting support to help early-stage companies build a stronger finance and compliance foundation from the beginning.',
        'source_text' => 'We are a leading start-up consulting firm offering powerful solutions to help you make a lasting impact in your industry and accelerate growth to early-stage companies.',
        'image' => 'assets/img/myimage/01_Startup_Solutions.jpg',
        'thumb' => 'assets/img/myimage/01_Startup_Solutions.jpg',
        'icon' => 'assets/img/corporateconsulting/icon/vl-service-icon-5.3.png',
        'stage' => 'Incorporation and early growth',
        'capabilities' => ['Business setup guidance', 'Finance process setup', 'Compliance coordination', 'Cash-flow planning', 'MIS foundation', 'Founder decision support'],
        'situations' => ['New company setup needs finance and compliance clarity.', 'Founders need reporting discipline before scaling.', 'Early teams need finance support without building a full internal department.'],
        'deliverables' => ['Finance setup roadmap', 'Compliance action list', 'Initial reporting cadence', 'Budget and cash-flow templates'],
    ],
    'virtual-cfo' => [
        'title' => 'Virtual CFO Services',
        'short' => 'CFO-level finance guidance, planning, controls, MIS, compliance, and decision support without building a full internal CFO office.',
        'overview' => 'Virtual CFO Services assist businesses in resolving complex business challenges with comprehensive finance leadership. The service helps companies manage books, create budgets, monitor finances, improve reporting discipline, and access experienced financial professionals in a flexible model.',
        'source_text' => 'Our Virtual CFO Services assist businesses in resolving complex business challenges and help to improve their performance. The cornerstone of our virtual CFO services is financial planning and analysis.',
        'image' => 'assets/img/myimage/02_Virtual_CFO_Services.jpg',
        'thumb' => 'assets/img/myimage/02_Virtual_CFO_Services.jpg',
        'icon' => 'assets/img/corporateconsulting/icon/vl-service-icon-5.1.png',
        'stage' => 'Growth and scaling',
        'capabilities' => ['Financial planning and analysis', 'Accounting system review', 'Accounting records and standards support', 'Financial and cash-flow projections', 'Budgeting and periodic review', 'Debtor and creditor management', 'Risk assessment', 'Compliance assurance', 'MIS reporting', 'Internal control review', 'Debt planning', 'Audit support'],
        'situations' => ['Leadership needs regular finance insight.', 'The company is scaling faster than its finance systems.', 'Founders need a finance partner for strategic decisions.', 'A business needs CFO support on demand rather than a full-time CFO.', 'Management needs better budgeting, forecasting, internal control, and compliance discipline.'],
        'deliverables' => ['Monthly MIS pack', 'Budget and forecast model', 'Cash-flow projection review', 'Accounting system improvement notes', 'Risk and compliance action list', 'Audit support tracker', 'Internal control recommendations', 'Debt planning summary'],
        'detail_sections' => [
            [
                'title' => 'How a Virtual CFO assists the business',
                'items' => [
                    'Reviews the existing accounting system and recommends improvements.',
                    'Helps maintain accounting records in line with applicable accounting standards.',
                    'Builds growth-oriented financial plans and identifies funding requirements.',
                    'Prepares financial projections using income statements and financial statements.',
                    'Tracks budgeting progress and reviews budget performance periodically.',
                    'Reviews cash-flow projections so the business can plan future commitments.',
                    'Assesses financial risks and helps reduce risk levels that may affect long-term business performance.',
                ],
            ],
            [
                'title' => 'Why companies choose Virtual CFO support',
                'items' => [
                    'Cost-effective CFO-level support without hiring a full-time senior finance leader.',
                    'On-demand or part-time engagement based on the company’s needs.',
                    'Quick integration with the existing team and finance process.',
                    'Better forecasting for budgets, financial decisions, and growth planning.',
                    'Compliance assurance across accounting, taxation, and regulatory requirements.',
                ],
            ],
            [
                'title' => 'Additional Virtual CFO benefits',
                'items' => [
                    'Financial advisory and planning support for senior management.',
                    'Break-even analysis and cost management support.',
                    'Accounting policy and procedure support for internal controls.',
                    'Corporate governance and applicable compliance support.',
                    'Year-end accounts closure, filing coordination, and audit query support.',
                ],
            ],
        ],
    ],
    'debt-fundraising' => [
        'title' => 'Debt Fundraising',
        'short' => 'Structured debt support for working capital, expansion, acquisition, and project financing needs.',
        'overview' => 'Finwert helps businesses prepare for and navigate debt fundraising requirements with structured lender-readiness support.',
        'source_text' => 'Structured debt solutions for working capital, business expansion, acquisitions, and project financing needs.',
        'image' => 'assets/img/myimage/03_Debt_Fundraising.jpg',
        'thumb' => 'assets/img/myimage/03_Debt_Fundraising.jpg',
        'icon' => 'assets/img/corporateconsulting/icon/vl-service-icon-5.2.png',
        'stage' => 'Working capital and expansion',
        'capabilities' => ['Debt requirement assessment', 'Lender-readiness support', 'Financial information preparation', 'Term sheet review support', 'Coordination through closure', 'Post-sanction documentation support'],
        'situations' => ['The business needs working capital lines.', 'Expansion requires structured debt.', 'Management needs lender-ready financial information.'],
        'deliverables' => ['Debt readiness note', 'Financial information pack', 'Lender query support', 'Documentation checklist'],
    ],
    'growth-capital' => [
        'title' => 'Capital Market, Fundraising & IPO Advisory',
        'short' => 'Strategic capital raising, equity fundraising, debt financing, IPO readiness, and capital structure advisory for scaling companies.',
        'overview' => 'Finwert supports companies at every financial stage, including expansion, stability, long-term value creation, pre-IPO readiness, and public market preparation. The practice helps identify, structure, and execute funding solutions aligned with business objectives.',
        'source_text' => 'Strategic equity fundraising and IPO advisory to help businesses scale, strengthen investor confidence, and create long-term value.',
        'image' => 'assets/img/myimage/04_Growth_Capital_Fundraising.jpg',
        'thumb' => 'assets/img/myimage/04_Growth_Capital_Fundraising.jpg',
        'icon' => 'assets/img/corporateconsulting/icon/vl-service-icon-5.3.png',
        'stage' => 'Scaling, pre-IPO, and listing readiness',
        'capabilities' => ['End-to-end fundraising execution', 'Targeted investor identification', 'Investment narrative and pitch storytelling', 'Valuation readiness and financial strength review', 'IPO readiness assessment', 'Financial and compliance preparation', 'Listing strategy and documentation support', 'Working capital loan solutions', 'Term loans and project financing', 'Loan restructuring and refinancing support', 'Loan against listed securities syndication', 'Optimized lender negotiations'],
        'situations' => ['The company is preparing to raise equity capital.', 'Leadership needs investor-grade financial information.', 'A business is moving toward pre-IPO or listing readiness.', 'The company needs working capital, project finance, bridge funding, or custom debt structures.', 'Existing debt terms need to be assessed, restructured, or refinanced for improved cash flow.'],
        'deliverables' => ['Investor readiness roadmap', 'Financial model inputs', 'Fundraising information pack', 'Investment narrative and pitch support', 'IPO readiness checklist', 'Debt financing requirement note', 'Loan restructuring assessment', 'Due diligence tracker'],
        'detail_sections' => [
            [
                'title' => 'Equity fundraising',
                'items' => [
                    'End-to-end fundraising execution for companies seeking growth capital.',
                    'Targeted investor identification aligned with business stage and sector.',
                    'Valuation readiness and financial strength review.',
                    'Investment narrative and pitch storytelling for investor confidence.',
                    'IPO readiness and listing support where the business is preparing for public markets.',
                ],
            ],
            [
                'title' => 'IPO advisory',
                'items' => [
                    'IPO readiness assessment across finance, compliance, governance, and reporting.',
                    'Financial and compliance preparation for the public market journey.',
                    'Listing strategy and documentation support.',
                    'Pre-IPO governance advisory to strengthen capital market preparedness.',
                ],
            ],
            [
                'title' => 'Debt financing and restructuring',
                'items' => [
                    'Working capital loan solutions for operating continuity.',
                    'Term loans and project financing for expansion and business operations.',
                    'Short-term and bridge funding support.',
                    'Comprehensive debt term assessment and lender negotiation.',
                    'Refinancing support for improved terms and cash-flow optimization.',
                ],
            ],
            [
                'title' => 'Loan against listed securities',
                'items' => [
                    'Loan syndication secured by listed securities to unlock liquidity without equity dilution.',
                    'Customized facility structuring based on liquidity and ownership requirements.',
                    'Regulatory-aligned execution support and optimized lender negotiations.',
                ],
            ],
        ],
    ],
    'accounting-financial' => [
        'title' => 'Accounting & Financial Services',
        'short' => 'End-to-end finance and accounting solutions for cleaner books and better reporting.',
        'overview' => 'Accounting and financial services help businesses maintain accurate records, useful reports, and stronger finance processes.',
        'source_text' => 'Our Accounting & Financial Services are the key to any business. We offer end-to-end finance and accounting solutions.',
        'image' => 'assets/img/myimage/05_Accounting_Financial_Services.jpg',
        'thumb' => 'assets/img/myimage/05_Accounting_Financial_Services.jpg',
        'icon' => 'assets/img/corporateconsulting/icon/vl-service-icon-5.4.png',
        'stage' => 'Recurring finance operations',
        'detail_url' => 'service-single-accounting.php',
        'capabilities' => ['Bookkeeping and accounting', 'MIS and budgeting', 'Payroll processing', 'Bank process management', 'Financial statements', 'GAAP to IND AS support'],
        'situations' => ['Books need clean-up or recurring discipline.', 'Management needs monthly MIS.', 'The company is preparing for audit, fundraising, or due diligence.'],
        'deliverables' => ['Monthly accounting reports', 'MIS dashboards', 'Payroll summaries', 'Financial statement schedules'],
    ],
    'due-diligence' => [
        'title' => 'Due Diligence',
        'short' => 'Risk review and financial analysis for transactions, investments, and business decisions.',
        'overview' => 'Finwert supports due diligence by analyzing potential risks and reviewing historical and current financial performance.',
        'source_text' => "We analyze the potential risks and forecast the future based on the company's historical and current financial performance.",
        'image' => 'assets/img/myimage/06_Due_Diligence.jpg',
        'thumb' => 'assets/img/myimage/06_Due_Diligence.jpg',
        'icon' => 'assets/img/corporateconsulting/icon/vl-service-icon-5.1.png',
        'stage' => 'Transactions and decision support',
        'capabilities' => ['Financial review', 'Risk identification', 'Historical performance analysis', 'Quality of information review', 'Transaction support', 'Management query support'],
        'situations' => ['Investors or lenders need financial review.', 'A transaction needs risk visibility.', 'Management wants independent finance analysis.'],
        'deliverables' => ['Due diligence issue list', 'Financial review summary', 'Risk notes', 'Management information request list'],
    ],
    'legal-secretarial' => [
        'title' => 'Legal & Secretarial Services',
        'short' => 'Company incorporation, secretarial support, and governance-related coordination.',
        'overview' => 'Finwert provides legal and secretarial services that support company incorporation, governance, and business growth.',
        'source_text' => 'We specialize in private and public company incorporation. The legal and secretarial services we provide are crucial to secretarial and the growth of your business.',
        'image' => 'assets/img/myimage/07_Legal_Secretarial_Services.jpg',
        'thumb' => 'assets/img/myimage/07_Legal_Secretarial_Services.jpg',
        'icon' => 'assets/img/corporateconsulting/icon/vl-service-icon-5.2.png',
        'stage' => 'Incorporation, governance, and compliance',
        'capabilities' => ['Company incorporation support', 'Secretarial compliance coordination', 'Board and filing support', 'Governance documentation', 'Regulatory process support', 'Corporate record maintenance'],
        'situations' => ['A company needs incorporation support.', 'Secretarial records and filings need better discipline.', 'A growing company needs stronger governance documentation.'],
        'deliverables' => ['Incorporation checklist', 'Secretarial compliance tracker', 'Board documentation support', 'Corporate records action list'],
    ],
    'tax-advisory' => [
        'title' => 'Tax Advisory Services',
        'short' => 'Tax planning and advisory support to help businesses navigate taxation complexity.',
        'overview' => 'Finwert helps clients navigate taxation complexity with practical tax advisory support aligned to business needs.',
        'source_text' => "We deliver optimal solutions through our Tax Advisory Services. To ensure your business's success, we help our clients navigate the complexities of taxation.",
        'image' => 'assets/img/myimage/08_Tax_Advisory_Services.jpg',
        'thumb' => 'assets/img/myimage/08_Tax_Advisory_Services.jpg',
        'icon' => 'assets/img/corporateconsulting/icon/vl-service-icon-5.4.png',
        'stage' => 'Compliance and advisory',
        'capabilities' => ['Tax advisory', 'Compliance review support', 'Transaction tax coordination', 'Tax impact analysis', 'Documentation support', 'Management query support'],
        'situations' => ['The business needs clarity on tax impact.', 'Transactions require tax review.', 'Compliance routines need stronger oversight.'],
        'deliverables' => ['Tax advisory note', 'Compliance action list', 'Tax impact summary', 'Documentation checklist'],
    ],
    'corporate' => [
        'title' => 'Corporate Services',
        'short' => 'Strategic guidance and digital solutions for corporate finance and business goals.',
        'overview' => 'Corporate Services bring together strategic guidance and digital solutions to help businesses pursue their goals with better financial clarity.',
        'source_text' => 'With our strategic guidance and digital solutions, we can help your business achieve its goals.',
        'image' => 'assets/img/myimage/09_Corporate_Services.jpg',
        'thumb' => 'assets/img/myimage/09_Corporate_Services.jpg',
        'icon' => 'assets/img/corporateconsulting/icon/vl-service-icon-5.3.png',
        'stage' => 'Corporate finance and business support',
        'capabilities' => ['Strategic finance support', 'Business planning', 'Process advisory', 'Digital finance workflows', 'Performance review support', 'Management reporting'],
        'situations' => ['A company needs strategic finance support.', 'Management wants cleaner business planning.', 'Corporate processes need better reporting and coordination.'],
        'deliverables' => ['Corporate finance action plan', 'Business review pack', 'Process improvement notes', 'Management reporting framework'],
    ],
];

function finwert_service_url(string $slug, array $service): string
{
    return $service['detail_url'] ?? 'service-single.php?service=' . urlencode($slug);
}
